### PR TITLE
Update URLs and views, modify browser_info.html template for show the…

### PR DESCRIPTION
**Pull request by aliskycloud**
Update URLs and views, modify browser_info.html template 
for show the user's browser information, IP and country

┆Issue is synchronized with this [Trello card](https://trello.com/c/bnJPQ3OR) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by millad90s** [comment]
you missed requirements.txt file. we need to have the list of all python packages in our project. 
please have a look at this closed MR:
https://github.com/millad90s/webDict/pull/6

**Comment by millad90s** [comment]
@aliskycloud 
Any update on this ?

**Comment by aliskycloud** [comment]
Yes, You are coorect.
I have to edit it

**Comment by aliskycloud** [comment]
I applied the changes and pushed

**Comment by millad90s** [comment]
Looks good to me

**Review by millad90s — APPROVED** [review]
Looks good to me

**Pull request merged**
